### ISSUE TITLE
Contradict between Readme, and working directory

### ISSUE THREAD

**Issue by agn-7** [tsinghua-rll/VoxelNet-tensorflow#47]
In your README in Usage section mentioned:

> make sure your working directory looks like this

> ```
> ├── build   <-- Cython build file
> ├── model   <-- some src files
> ├── utils   <-- some src files
> ├── setup.py   
> ├── config.py   
> ├── test.py   
> ├── train.py   
> ├── train_hook.py   
> ├── README.md    
> └── data    <-- KITTI data directory 
>     └── object 
>         ├── training   <-- training data
>         |   ├── image_2   
>         |   ├── label_2   
>         |   └── velodyne  
>         └── testing  <--- testing data
>             ├── image_2   
>             ├── label_2   
>             └── velodyne  
> ```

But I can't find "data" folder.

**Comment by gdicker1** [comment]
This directory (and sub-directories) should be created by the user. Since the dataset is near 29 GB, you can't upload it to github.
